apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: {{ .Values.clickhouse.name }}
spec:
  configuration:
    users:
      admin/networks/ip: "::/0"
      admin/password: qwerty
      admin/profile: default
      admin/grants/query:
        - "GRANT ALL ON *.*"
    clusters:
      - name: {{ .Values.clickhouse.name }}
        templates:
          podTemplate: pod-template-with-volumes
        layout:
          shardsCount: {{ .Values.clickhouse.shardsCount }}
          replicasCount: {{ .Values.clickhouse.replicasCount }}
  templates:
    podTemplates:
      - name: pod-template-with-volumes
        spec:
          containers:
            - name: {{ .Values.clickhouse.containername }}
              image: {{ .Values.clickhouse.image.repository }}:{{ .Values.clickhouse.image.tag }}
              volumeMounts:
                - name: data-storage-vc-template
                  mountPath: /var/lib/clickhouse
                - name: log-storage-vc-template
                  mountPath: /var/log/clickhouse-server
    volumeClaimTemplates:
      - name: data-storage-vc-template
        spec:
          storageClassName: {{ .Values.proceset.MemoryData }}
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ .Values.proceset.storageClassName }}
      - name: log-storage-vc-template
        spec:
          storageClassName: {{ .Values.proceset.MemoryLog }}
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ .Values.proceset.storageClassName }}
