apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.proceset.name }}
  name: {{ .Values.proceset.name }}
spec:
  ports:
    - name: "http"
      port: 8010
      targetPort: 8010
  selector:
    app: {{ .Values.proceset.name }}
